version: 2

jobs:
  setup-dependencies:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: ruby-gems-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  rubycritic:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - run: bundle exec rubycritic ./app

      - type: shell
        command: |
          bundle exec rubycritic ./app -f json lib -f html --no-browser
      - run:
        name: Coverage notification
        command: bundle exec rake circleci:report_coverage

      - store_artifacts:
          path: ./tmp/rubycritic

  test:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: bundle exec rails test

workflows:
  version: 2
  development:
    jobs:
      - setup-dependencies
      - rubycritic:
          requires:
            - setup-dependencies
      - test:
          requires:
            - setup-dependencies
