version: 2

jobs:
  setup-dependencies:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: ruby-gems-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  rubycritic:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rubycritic ./app
      - store_artifacts:
          path: ./tmp/rubycritic

  test:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-{{ checksum "Gemfile.lock" }}
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  development:
    jobs:
      - setup-dependencies
      - rubycritic:
          requires:
            - setup-dependencies
      - test:
          requires:
            - setup-dependencies
